title: Prashant Gupta
email: contact@imprashant.com
description: "Data Scientist with software developement ethics"
baseurl: ""
url: "https://imprashant.com"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - vendor

paginate: 9
paginate_path: "/page/:num/"

googleAnalyticsId: UA-120508304-1  

gems:
  - jekyll-paginate
  - jekyll-github-metadata
  - jemoji

excerpt_separator: <!--more-->

collections:
  tv:
    output: true

defaults:
  - scope:
      path: ""
      type: tv
    values:
      layout: tv
      permalink: /video/:title

future: true

# Serving
detach:  false
port:    4100
host:    0.0.0.0

# Staticman
staticmanUrl: https://api.staticman.net/v2/entry/prashantitis/prashantitis.github.io/master/comments
