safe: true
lsi: false

url: https://imprashant.com
enforce_ssl:  imprashant.com
author:
  name: Prashant Gupta
title: Prashant Gupta - AI freak!
permalink: /blog/:year/:month/:title/
highlighter: rouge

gem 'jemoji'

