# Site settings
title:       Prashant Gupta
email:       prashantgpt91@gmail.com
author:      Prashant Gupta
description: "A brief About me"
baseurl:     ""
url:         "http://x0v.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: true

# Social icons
show_social_icons: true
github_username: 'x0v'	
stackoverflow_id: 
twitter_username: 'prashantgpt91'
google_plus_id:
linkedin_username: 'prashantgpt91'
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  hard_wrap: false
  extensions: ['smart', 'tables', 'with_toc_data', "highlight"]
permalink:    pretty
paginate:     5
sass:
  compressed: true

gems: [jekyll-paginate]
